# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCliSwitchbot < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/ChikaKakazu/go-cli-switchbot/releases/download/v0.3.0/go-cli-switchbot_Darwin_x86_64.tar.gz"
      sha256 "db97405a0a8de20d0dae4e881dfe23fe7244c578b39d8f9f70ade135de51afcf"

      def install
        bin.install "go-cli-switchbot"
      end
    end
    on_arm do
      url "https://github.com/ChikaKakazu/go-cli-switchbot/releases/download/v0.3.0/go-cli-switchbot_Darwin_arm64.tar.gz"
      sha256 "ea634c75a01337c9efbe361413a1271f7492a33f9dc28fa258d599495b1f82e4"

      def install
        bin.install "go-cli-switchbot"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ChikaKakazu/go-cli-switchbot/releases/download/v0.3.0/go-cli-switchbot_Linux_x86_64.tar.gz"
        sha256 "719c39e130362155efec8b0afb4b1908207f7324a7ae53e5763407a8db9c0853"

        def install
          bin.install "go-cli-switchbot"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ChikaKakazu/go-cli-switchbot/releases/download/v0.3.0/go-cli-switchbot_Linux_arm64.tar.gz"
        sha256 "87c77cc7cfbf6f596e799fb7451d1535ecfe54eefcd17a05adffa170ed0beee8"

        def install
          bin.install "go-cli-switchbot"
        end
      end
    end
  end
end
