# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCliSwitchbot < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/ChikaKakazu/go-cli-switchbot/releases/download/v0.2.0/go-cli-switchbot_Darwin_x86_64.tar.gz"
      sha256 "14e6d92b9773de9cf096aded1ce6604070844660e2dc2e779ae8cc4e7bfebe89"

      def install
        bin.install "go-cli-switchbot"
      end
    end
    on_arm do
      url "https://github.com/ChikaKakazu/go-cli-switchbot/releases/download/v0.2.0/go-cli-switchbot_Darwin_arm64.tar.gz"
      sha256 "cd93d1bcf6ba93e2bcffd94551acf5444d6844c2bc194afe2df7bf313eb7e92c"

      def install
        bin.install "go-cli-switchbot"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ChikaKakazu/go-cli-switchbot/releases/download/v0.2.0/go-cli-switchbot_Linux_x86_64.tar.gz"
        sha256 "e16a28d31ec43cb393a84d1a1b3d9c846fd2d0c03c62b6f06381ae44bcad7f87"

        def install
          bin.install "go-cli-switchbot"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ChikaKakazu/go-cli-switchbot/releases/download/v0.2.0/go-cli-switchbot_Linux_arm64.tar.gz"
        sha256 "cd940ebd46cf81b552772c79205e12c44ccfac07d2313b2c74566b285eadc226"

        def install
          bin.install "go-cli-switchbot"
        end
      end
    end
  end
end
